version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_PASSWORD: new_password
      POSTGRES_DB: app_sodexo
      POSTGRES_USER: new_ignacio
    volumes:
      - ./postgres:/var/lib/postgresql/data
    ports:
      - '5433:5432'
